In [5]:
import seaborn as sns
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
pd.options.plotting.backend="plotly"
%matplotlib inline

In [6]:
df=pd.read_csv(r'C:\Users\Admin\OneDrive\Desktop\data.csv')

In [7]:
df.head()

,Unnamed: 0,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,0,158023,L. Messi,31,https://cdn.sofifa.org/players/4/19/158023.png,Argentina,https://cdn.sofifa.org/flags/52.png,94,94,FC Barcelona,...,96.0,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0,€226.5M
1,1,20801,Cristiano Ronaldo,33,https://cdn.sofifa.org/players/4/19/20801.png,Portugal,https://cdn.sofifa.org/flags/38.png,94,94,Juventus,...,95.0,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0,€127.1M
2,2,190871,Neymar Jr,26,https://cdn.sofifa.org/players/4/19/190871.png,Brazil,https://cdn.sofifa.org/flags/54.png,92,93,Paris Saint-Germain,...,94.0,27.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0,€228.1M
3,3,193080,De Gea,27,https://cdn.sofifa.org/players/4/19/193080.png,Spain,https://cdn.sofifa.org/flags/45.png,91,93,Manchester United,...,68.0,15.0,21.0,13.0,90.0,85.0,87.0,88.0,94.0,€138.6M
4,4,192985,K. De Bruyne,27,https://cdn.sofifa.org/players/4/19/192985.png,Belgium,https://cdn.sofifa.org/flags/7.png,91,92,Manchester City,...,88.0,68.0,58.0,51.0,15.0,13.0,5.0,10.0,13.0,€196.4M

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18207 entries, 0 to 18206
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         18207 non-null  object
 1   Age          18207 non-null  int64
 2   Nationality  18207 non-null  object
 3   Overall      18207 non-null  int64
 4   Potential    18207 non-null  int64
 5   Club         17966 non-null  object
 6   Value        18207 non-null  object
dtypes: int64(3), object(4)
memory usage: 995.8+ KB

In [25]:
df.describe()

                Age       Overall     Potential
count  18207.000000  18207.000000  18207.000000
mean      25.122206     66.238699     71.307299
std        4.669943      6.908930      6.136496
min       16.000000     46.000000     48.000000
25%       21.000000     62.000000     67.000000
50%       25.000000     66.000000     71.000000
75%       28.000000     71.000000     75.000000
max       45.000000     94.000000     95.000000

In [9]:
df = df[['Name', 'Age', 'Nationality', 'Overall', 'Potential', 'Club', 'Value']]
df.head()

,Name,Age,Nationality,Overall,Potential,Club,Value
0,L. Messi,31,Argentina,94,94,FC Barcelona,€110.5M
1,Cristiano Ronaldo,33,Portugal,94,94,Juventus,€77M
2,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,€118.5M
3,De Gea,27,Spain,91,93,Manchester United,€72M
4,K. De Bruyne,27,Belgium,91,92,Manchester City,€102M

In [13]:
df.plot.bar()

ValueError: Plotly Express cannot process wide-form data with columns of different type.

In [14]:
sns.barplot(x='Age',y='Potential',data='data')

AttributeError: 'str' object has no attribute 'get'